### ISSUE TITLE
Meeting Discussion

### ISSUE THREAD

**Issue by dhakal0kushal** [yaya-BL/Restaurants_self-order_app#25]
### Project Structure we currently have
- A user can create a shop
- He can add a branch to the shop
- He can add/ edit/ delete a category and items in that category

### The Problem that it creates /  the feature that we will be missing

- Multiple users won't be able to add/ edit a particular shop's contents. i.e only the user who created a shop will be able to create a category and only the user who created that category will be able to edit the category. The same is for adding the items to the category. 
- A user cannot be assigned to multiple branches. i.e a user, "smith", cannot be assigned to manage the branches of a shop that he is part of. "Smith" needs to create multiple accounts for those multiple branches to manage the branches.
- We will miss out on the feature every other modern web apps provides and the users won't even bother to create a separate account to manage another branch. 

### If it's not good then what's the solution?

The solution is simple. We implement those functionalities that we are lacking.(of course, the development process will be complex and will take extra time but why not). The functionalities that we need are: 

- Let the user create multiple shops and inside shop multiple branches. Of course, we will need to verify every shop created before we show them to the customer. This way the user won't need to create yet another account if he wants to add a new shop.
- Let a user manage multiple branches from a single account. The shop owner won't spend his time adding the products to the shop. He will need to have a system to assign the permission to another user. That other user is someone whose work is to manage the branches of the restaurant. For example, a person has a Facebook account, he can be assigned to manage different pages of different businesses. The business owner won't keep editing the page contents and thinking about what and when to post the next update. 
- Let multiple users manage the same branch. This is a simple one, we need to have different users with different permissions in a single branch. A single branch can have different managers, employees, and staff. 

### Country filters 
I ask @SazidAhmed to add something here

**Comment by yaya-BL** [comment]
As we discussed, we shall create a new user_type -> Branch-admin
and the Shop-Owner will be able to assign Branch-admin and Branch-Employee users to specific branch
with keeping in mind that each branch can have ONLY one Branch-Employee and multiple Branch-admin
and Branch-admin can manage multiple branches

1          Customer        See mobile customer view
2          Shop-Owner      See Mobile employee view, and portal to manage all the branches (shop super admin) Assign employee and branch admin to branches.
3      Branch-Employee   Only mobile employee view
4          Branch-admin    See Mobile employee view, and portal to manage assigned branch
